<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <meta name="generator" content="CoffeeCup HTML Editor (www.coffeecup.com)">
    <meta name="dcterms.created" content="Tue, 02 Mar 2021 04:49:31 GMT">
    <meta name="description" content="MMORPG Game of the year 'Dragon Nest Adventure'!">
    <meta name="keywords" content="Dragon Nest Adventure, DNA, Dragon Nest A">
	<link rel="shortcut icon" href="../favicon.ico" type="image/x-icon">
	<link rel="stylesheet" href="../lib/css/register.css" type="text/css">
	<link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.0.2/dist/tailwind.min.css" type="text/css">
	<link href="https://tailwindcomponents.com/css/component.checkboxes.css" rel="stylesheet">
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"url": "http://127.0.0.1",
		"sameAs": []
}</script>
<script src="../lib/jquery.min.js"></script>
	<script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <title>Register - Dragon Nest Adventure</title>
  </head>
<body>

<header class="contain">
  <div class="containernav">
   <a class="navlink">Dragon Nest Adventure</a>
   
   
   <nav>
    <ul>
	 <li><a href="/">Home</a></li>
	 <li><a href="/register">Register</a></li>
	 <li><a href="/login">Login</a></li>
	 <li><a href="/downloads">Download</a></li>
	</ul>
   </nav>
  
  </div>
</header>

<div id="myModal" class="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-content">
    <span class="close">&times;</span>
	<div style="border-bottom: 1px solid #ffffff">
    <h1 class="termsyAgreement">Condition and Terms of Agreement</h1>
	<br>
	</div>
	<br>
	<div class="modal-body">
	
	Effective Date : January 1st, 2021

Adventure Games LLC Inc. (“Adventure Games”) offers online games and various interactive services (forums, portals, etc., collectively the “Service”). The Service is conditioned on your acceptance of the following agreements:

<ul><li>The End User License Agreement (“EULA”) that applies to the interactive software entertainment product and services offered by Adventure Games (e.g., our games);</li><li>Privacy Policy;</li><li>These Terms of Use (“ToU”);</li><li>Additional terms that govern particular features or offers (for example, our Code of Conduct, our User Generated Content policy, etc.) (“Additional Terms”). A full list of Additional Terms can be found here; and</li><li>Applicable third party terms that you may need to accept to utilize certain parts of the Service (e.g., payment processor terms; third party distribution platform terms, integration of social networking profiles, etc.).</li></ul>
The agreements are listed in terms of their priority and application to you. In the event of a conflict between provisions contained within any particular agreement, the agreement that is listed first shall control. For example, in the event of a conflict between these Terms of Use and the Privacy Policy, the Privacy Policy shall control. In the event of a conflict between the Additional Terms and the EULA, the EULA will control.

By accepting these Terms of Use, you are accepting all agreements that are part of the Service.

<strong>1. Limitation of Use</strong>
<span>Unless otherwise provided, the Service is only for your personal purpose, not any commercial use. You may not modify, copy, distribute, transmit, display, perform, license, create any derivative work from, sell or transfer any information, software, product or service known or obtained from the Service.</span>
<strong>2. Registration</strong>
<span>2.1 Registration Process
<span>The Service requires you to create an account with a username and password. When you are registering for the account, you agree that you will (i) provide accurate, up-to-date and complete information; (ii) maintain and promptly update the account information provided by you; (iii) maintain the confidentiality and security of your username and password; (iv) accept all risks and responsibilities with any and all authorized or unauthorized access to your account; and (v) immediately notify us if you discover, acknowledge or otherwise suspect any unauthorized use of your account information.</span></span><span>2.2 Registration Information
<span>For registration, you must provide us with certain information about yourself, including, but not limited to, your name, email address, birthday including information requested by us. Your information will be disposed and managed by us in accordance with Adventure Game’s Privacy Policy. You may have the option to provide us with the information of your social media network and use the information in order to log in the account. Once you submitted your information, we may send you an email to verify the information you submitted. You must click on the link or follow the instruction/process in the verifying email to complete the registration process.</span></span><span>2.3 Account Eligibility
<span>You may establish an account only if (i) you are an adult as a natural person in your country of residence and you are not any legal or business entities such as agency, partnership or corporation(including LLC); (ii) you are at least thirteen (13) years of age; (iii) if you are not of the age of majority in your country of residence (generally eighteen (18) years old), you must have your parents or legal gardian’s consent to register. If we request any evidence of the consent, you must submit the evidence immediately; (iv) you are not a person prohibited or restricted by Adventure Game’s regulations and/or policies from playing the Service. If we becomes aware that you registered or created an account in violation of the foregoing eligible requirement, Adventure Games, at its sole discretion, reserves the right to suspend, close and/or delete the account.</span></span><span>2.4 <!-- ???? -->Email,<!-- // ???? --> Username, Password and Limitation
<span>As a necessary part of the registration process, you will be asked to use your username and password for use of the Service. We reserve the right to refuse access to the Service or to prohibit your use of <!-- ???? -->a email that is of disposable nature and<!-- // ???? --> a username that: (i) impersonates someone else, including, but not limited to, other user; (ii) is or may be illegal or may be protected by trademark or other proprietary right law or may cause a confusion with others’; (iii) is or may be considered vulgar, defamatory(including libel or slander, etc.), obscene, hateful, racially, ethnically or otherwise offensive, including username which is sexual in nature; (iv) is or includes the name of popular or other’s proprietary icon, character name or religious deity or figure or your real name, surname or family name; (v) is or includes a name of drug, narcotic or other illegal activity, notorious figure, or (vi) is otherwise inappropriate subject to Adventure Games’s regulations or policies, regardless of our software’ ability to disallow the usename.</span></span><span>2.5 Security and Confidentiality Responsibility
<span>You must secure your account information for the use and confidentiality. You agree that you will not assign your right to access the Service by sharing your account information to any third party. YOU ARE RESPONSIBLE FOR MAINTAINING AND SECURING THE CONFIDENTIALITY OF YOUR ACCOUNT INFORMATION AND THE ALL RELATED ACTIVITIES INCLUDING SHARING YOUR ACCOUNT INFORMATION FOR THE SERVICE.</span></span><span>2.6 OWNERSHIP
<span>NOTWITHSTANDING ANYTHING TO THE CONTRARY HEREIN, YOU ACKNOWLEDGE AND AGREE THAT YOU SHALL HAVE NO OWNERSHIP OR OTHER PROPRIETARY INTEREST IN YOUR ACCOUNT. FURTHERMORE, YOU ACKNOWLEDGE AND AGREE THAT ANY AND ALL RIGHTS IN RELATION TO YOUR ACCOUNT SHALL FOREVER BE OWNED BY AND INURE TO THE BENEFIT OF Adventure Games. Adventure Games NEVER RECOGNIZE OR ALLOW THE TRANSFER OF ACCOUNTS BETWEEN PLAYERS. YOU SHALL NOT PURCHASE, SELL, GIFT OR TRADE ANY ACCOUNT, OR OFFER TO PURCHASE, SELL, GIFT OR TRADE ANY ACCOUNT AND SUCH ATTEMPT SHALL BE NULL AND VOID AND MAY RESULT IN THE FORFEITURE OF YOUR ACCOUNT.</span></span><span>2.7 Termination
<span>Adventure Games reserve, at its sole discretion, the right to terminate your access to any or all parts of the Service at any time, without any notice, if you fail to comply with these ToU.</span></span>
<strong>3. Terms of Sale</strong>
<span>These terms of sale do not apply to virtual currency obtained through a third party distribution platform (e.g., Steam). You must acknowledge and follow that any item or virtual currency obtained through a third party distribution platform is subject to the regulations, policies and/or agreement between you and the third party distribution platform.
You should carefully read the terms in this Section 3 and you acknowledge and agree that you are at least 18 years old or that you have the consent from your parents or a legal guardian to enter into this legal contract for sale.</span><span>3.1 Price
<span>any prices, quotations and descriptions made or referred to the Service do not constitute an offer and may be withdrawn or revised prior to Adventure Games’s express acceptance of your order at any time. Adventure Games reserves the right to notify you of any mistake or error in the prices, quotations or descriptions and revision for them. If you want to continue to enjoy the Service with your order, you acknowledge and agree that the Service will be provided in such revised ones.</span></span><span>3.2 Payment
<span>Various payment methods authorized by Adventure Games, such as credit card, debit card, mobile charge, pre-paid card may be available to you when you are obtaining EYE Cash and EYE Total (collectively “EYE CASH”) in the Service. You are solely responsible for all the payment of Federal, State and local taxes with the receipt or use of the in-game items which you purchases from Adventure Games.
YOU REPRESENT AND WARRANT TO Adventure Games THAT YOU ARE THE AUTHORIZED USER OF THE PAYMENT METHOD THAT IS USED TO PAY ANY AND ALL CHARGES/FEES APPLICABLE TO THE SERVICE. It means that you are solely responsible for all usages and purchases on your account unless the purchase is unlawful or fraudulent one by someone other than those authorized by you.</span></span><span>3.3 Currencies
<span>You may be able to choose USD to charge EYE CASH in online and you agree that USD 1 means 1,000 EYE CASH.</span></span><span>3.4 Virtual Currency
<span>You may visit in-game “cashshop” where you obtain Adventure Games’s virtual currency, as known as EYE CASH. EYE CASH has no “real world” value. You acknowledge and agree that EYE Cash has no “real world” value, is not real currency or any type of financial instrument and is not regarded as any sum of money from us. REGARDLESS OF THE CONSIDERATION OFFERED OR PAID IN EXCHANGE FOR VIRTUAL CURRENCY, YOU NEVER HAVE ANY OWNERSHIP RIGHT IN THE IN-GAME ITEMS OBTAINED WITH VIRTUAL CURRENCY.
Certain maximums depending number of transaction per day may apply to the Service. For example, your transaction may be limited to three (3) times per day, no more than USD 1,000 per day and no more than USD 2,000 per month. Adventure Games reserves, at its sole discretion, the right to change the maximum amount to charge EYE CASH at any time.</span></span><span>3.5 Virtual Items
<span>You may have the opportunity to purchase digital, in-game items or to exchange EYE CASH for the items. You acknowledge and agree that digital, in-game items has no “real world” value, is not your property and is not regarded as any sum of money from us. REGARDLESS OF THE CONSIDERATION OFFERED OR PAID IN EXCHANGE FOR VIRTUAL ITEMS, YOU NEVER HAVE ANY OWNERSHIP RIGHT IN THE ITEMS OBTAINED.</span></span><span>3.6 Extinguishment of EYE CASH
<span>EYE CASH will extinguish if you have not used EYE CASH in a year. For the purpose of this section only, “use” of EYE CASH means either purchasing virtual item or other digital good using EYE CASH or adding EYE CASH to your account.
For the calculating whether the account has not used EYE CASH in a year, the applicable month shall be the month in which the last use occurred until the end of the same calendar month in the next year.</span></span><span>3.7 Refund
<span>ANY CHARGED AND OTHER FEES ARE NOT REFUNDABLE IN PART OR IN WHOLE, INCLUDING, WITHOUT LIMITATION, UPON TERMIATION OF YOUR ACCOUNT, EXTINGUISHMENT OF YOUR EYE CASH FOR ANY REASON, TERMINATION OF THIS AGREEMENT AND/OR THE DISCONTINUATION OF THE SERVICE EXCEPT FOR SHUT-DOWN OF THE SERVICE, THE DISCONTINUATION/INCIDENT OF THE SERVICE BY A MATERIAL BREACH OF Adventure Games AND/OR YOUR CANCELLATION BASED ON A UNILATERAL CANCELLATION OF TRANSACTION BY CREDIT CARD COMPANY.</span></span><span>3.8 Change and Update
<span>Adventure Games may, at any time, change or update these ToU and the changed or updated ToU will apply to any and all subsequent purchases. YOU ACKNOWLEDGE AND AGREE THAT YOU WILL REVIEW THE TOU IN DETAIL BEFORE ANY YOUR PURCHASE.</span></span>
<strong>4. Use of the Service</strong>
<span>4.1 No Unlawful Use
<span>You represent and warrant that you shall not use the Service for any purpose that is unlawful or prohibited/restricted by these ToU. Also, you may not use the Service in any manner which could damage, disable, overburden, or impair, interfere the Service and/or any other user.</span></span><span>4.2 Code of Conduct (PLEASE REVIEW AND AGREE THE BELOW ATTACHMENT)
<span>Adventure Games has made available a Code of Conduct which applies to your use of the Service, including your use of the games offered by Adventure Games. You agree to comply with all applicable laws, rules and regulations. We reserve the right, in our sole discretion, to take any actions we deem necessary and appropriate to preserve the integrity of the Service. We further reserve the right to determine what conduct is outside the "spirit" of the Service and games provided therein.</span></span><span>4.3 No Misuse of Data
<span>You acknowledge and agree that you will not (i) obtain or attempt to obtain any information from the Service using any method not expressly permitted by Adventure Games; (ii) intercept, examine or otherwise observe any proprietary communications protocol used by the Service, whether through the use of a network analyzer, packet analyzer or other device; (iii) use any other software/tool to collect information from the Service, including without limitation information about your account, your character, virtual item, other player, or other Service’s related all data.</span></span><span>4.4 User Generated Content (PLEASE REVIEW AND AGREE THE BELOW ATTACHMENT)
<span>User Generated Content means all communications, images, sounds, and all the material and information that you upload or transmit through the Service, or that other users upload or transmit, including without limitation any chat text, gameplay clips, and content you make that is based on or utilizes Adventure Games’s intellectual property. All User Generated Content is subject to the User Generated Content Policy.
You agree and acknowledge that User Generated Content is specifically NOT governed by Adventure Games’s Privacy Policy, and instead is governed by this ToU.</span></span>
<strong>5. Intellectual Property Rights</strong>
<span>5.1 Infringement of Intellectual Property Rights
<span>You acknowledge and agree that the Service, the Website and the related content and other applications made available on the Service is exclusively owned by Adventure Games, its licensors or its affiliates and are lawfully protected by the applicable laws, rules and regulations and international treaties relating to copyrights, trademarks and other intellectual property rights. YOU NEVER HAVE ANY OWNERSHIP INTEREST IN SUCH PROPRIETARY SUBJECT MATTER PURSUANT TO THESE TOU OR ANY AND ALL AGREEMENT BETWEEN YOU AND Adventure Games OTHERWISE.</span></span><span>5.2 Indemnification and Termination
<span>You acknowledge and agree that you indemnify and hold harmless Adventure Games and its licensors, affiliates, directors, officers, employees and agents from any and all claims for losses, expenses and liabilities, including reasonable attorney’s fees in relation to such legal suits and actions etc.
If you are engaged or have engaged in infringement or we reasonably suspect that your use of the Service infringes Adventure Games’s or others’ intellectual property rights, we may, at our sole discretion, suspend, terminate or delete your account with or without prior notice to you.</span></span>
<strong>6. Software and Content on the Service</strong>
<span>6.1 License to Software and Content
<span>You may download or access to certain software and content for the Service subject to the following:
<span>(i) Adventure Games hereby grant you a personal, limited, revocable, non-sublicensable and non-exclusive license to intall a copy of any downloadable software or content under your legitimate control; and only to access and use the Service solely for personal, non-commercial purpose.</span><span>(ii) You may not i) copy software or content made available to the Service; ii) sell, rent, lease, license, distribute or otherwise transfer or make the Service available to any other person, in whole or in part, or use the Service in any commercial context; iii) make available, adapt, publicly perform, or publicly display the Service; iv) reverse engineer, derive source code, modify, decompile, disassemble, or create derivative works based on the Service in whole or in part; v) remove, disable or circumvent any proprietary notices, labels or access control technology contained on or within the Service or any portion thereof; vi) export or re-export the Service or any copy in violation of any applicable export restrictions or other laws or regulations.</span><span>(iii) You must keep intact all copyright and other proprietary contents/notices.</span><span>(iv) Software and content made available on the Service is owned by Adventure Games, its licensors or its affiliates and is protected by any and all applicable laws, rules and regulations and international treaty provisions. YOU ACKNOWLEDGE AND AGREE THAT ANY REPRODUCTION OR REDISTRIBUTION OF THE SOFTWARE AND CONTENT IS EXPRESSLY PROHIBITED BY LAWS, RULES AND REGULATIONS AND INTERNATIONAL TREATY PROVISIONS AND MAY RESULT IN SEVERE CIVIL AND CRIMINAL PENALTIES TO THE MAXIMUM EXTENT POSSIBLE.</span><span>(v) WITHOUT LIMITING THE FOREGOING, COPYING OR REPRODUCTION OF THE SOFTWARE TO ANY OTHER CONTENT FOR FURTHER REPRODUCTION OR REDISTRIBUTION IS EXPRESSLY PROHIBITED. THE SOFTWARE IS WARRANTED, IF AT ALL, ONLY ACCORDING TO THE TERMS OF THE LICENSE AGREEMENT. You acknowledge and agree that software, content and any related documentation and/or technical information is subject to applicable export control laws and regulations of the USA. You may not export or re-export the software, directly or indirectly, to any other countries that are subject to USA export restriction.</span></span></span><span>6.2 Termination of License
<span>The license in this Section 6 is conditioned on your compliance with all agreements applicable to you, and shall terminate upon the earlier of: (a) your breach of any part of these agreements; or (b) our termination of the Service or the removal of software or content to which the license applies. If you breach any provision of the agreements applicable to you, any license you have obtained will be automatically rescinded and terminated. In order to protect our rights some software or content made available through the Service may contain watermarks and/or be controlled by other digital rights management technologies, which will restrict how you may access and use that software or content. You may not remove, delete, or alter any watermark or other digital rights management technology or other information.</span>PLEASE REVIEW IN DETAIL AND AGREE THE BELOW ATTACHED END USER LICENSE AGREEMENT.</span>
<strong>7. LIABILITY DISCLAIMER</strong>
<span>THE SOFTWARE, SERVICES AND RELATED CONTENT INCLUDED IN OR AVAILABLE THROUGH THE SERVICE MAY INCLUDE INACCURACIES OR TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY ADDED TO THE INFORMATION HEREIN. Adventure Games, ITS LICENSORS, ITS AFFILIATES AND RESPECTIVE DEVELOPERS MAY MAKE IMPROVEMENTS AND/OR CHANGES IN THE SERVICE AT ANY TIME. INFORMATION RECEIVED VIA THE SERVICE SHOULD NOT BE RELIED UPON FOR PERSONAL, MEDICAL, LEGAL OR FINANCIAL DECISIONS AND YOU SHOULD CONSULT AN APPROPRIATE PROFESSIONAL FOR SPECIFIC ADVICE TAILORED TO YOUR SITUATION.
Adventure Games, ITS LICENSORS, ITS AFFILIATES AND RESPECTIVE DEVELOPERS MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, AND ACCURACY OF THE INFORMATION, SOFTWARE, SERVICES AND RELATED CONTENT CONTAINED ON THE SERVICE FOR ANY PURPOSE. ALL SUCH INFORMATION, SOFTWARE, SERVICES AND RELATED CONTENT ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND. Adventure Games, ITS LICENSORS, ITS AFFILIATES AND RESPECTIVE DEVELOPERS HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH REGARD TO THIS INFORMATION, SOFTWARE, SERVICES AND RELATED CONTENT, INCLUDING ALL IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.
YOU SPECIFICALLY AGREE THAT Adventure Games SHALL NOT BE RESPONSIBLE FOR UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA, ANY CONTENT OR DATA SENT OR RECEIVED OR NOT SENT OR RECEIVED, OR ANY TRANSACTIONS ENTERED INTO THROUGH THE SERVICE. YOU SPECIFICALLY AGREE THAT Adventure Games IS NOT RESPONSIBLE OR LIABLE FOR ANY THREATENING, DEFAMATORY, OBSCENE, OFFENSIVE OR ILLEGAL CONTENT OR CONDUCT OF ANY OTHER PARTY OR ANY INFRINGEMENT OF ANOTHER'S RIGHTS, INCLUDING INTELLECTUAL PROPERTY RIGHTS. YOU SPECIFICALLY AGREE THAT Adventure Games IS NOT RESPONSIBLE FOR ANY CONTENT SENT USING AND/OR INCLUDED IN THE SERVICE BY ANY THIRD PARTY.
IN NO EVENT SHALL Adventure Games, ITS LICENSORS, ITS AFFILIATE AND RESPECTIVE DEVELOPERS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF USE, DATA OR PROFITS, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR PERFORMANCE OF THE SERVICE, WITH THE DELAY OR INABILITY TO USE THE SERVICE OR ANY PART THEREOF, THE PROVISION OF OR FAILURE TO PROVIDE SERVICES, OR FOR ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED CONTENT OBTAINED THROUGH THE SERVICE, OR OTHERWISE ARISING OUT OF THE USE OF THE SERVICE, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF Adventure Games, ITS LICENSORS, ITS AFFILIATES OR RESPECTIVE DEVELOPERS HAVE BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL, INCIDENTAL OR OTHER FORMS OF DAMAGES, SOME OR ALL OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SERVICE, OR WITH ANY OF THE TERMS OF THE APPLICABLE AGREEMENTS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SERVICE.</span>
<strong>8. THIRD PARTY SERVICES AND CONTENT</strong>
<span>8.1 Advertising.
<span>The Service may incorporate third-party technology that enables advertising on our websites, in our games, or through other means of communication. As part of this process, Adventure Games and/or its authorized third party advertisers may collect standard information that is sent when your personal computer connects to the Internet including your Internet protocol (IP) address. More information about such practices can be found in our Privacy Policy.</span></span><span>8.2 Social Media.
<span>If you are a registered user of certain social media networks (e.g., Facebook, Twitter, etc.), you may have the opportunity to utilize your social media account data to take advantage of certain features on the Service (e.g., friend search). Your social media account is subject to separate terms and conditions provided by the social media network at issue. If you utilize a social media account connect feature, others will be able to associate your user ID and/or in-game name with your real name on the Service. You hereby acknowledge that neither Adventure Games nor the social media network at issue is responsible for any liability as a result of your use of the Service and that the Service is in no way sponsored, endorsed or administered by any particular social media network.</span></span><span>8.3 Links to Third Party Sites.
<span>The Service may contain links to or feeds from websites controlled by third parties (“Linked Site(s)”). The Linked Sites are not under the control of Adventure Games and Adventure Games is not responsible for the contents of any Linked Site, including without limitation any link contained in a Linked Site, or any changes or updates to a Linked Site or any information transmitted on a Linked Site. Adventure Games is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by Adventure Games of the site or any association with its operators.
Any dealings with third parties (including advertisers) included within or available via a link from the Service or participation in promotions, including the delivery of and the payment for goods and services, and any other terms, conditions, warranties or representations associated with such dealings or promotions, are solely between you and the advertiser or other third party. Adventure Games shall not be responsible or liable for any part of any such dealings or promotions.</span></span>
<strong>9. MODIFICATION OF THE ToU.</strong>
<span>Adventure Games reserves the right to change the ToU at any time. You are responsible for regularly reviewing these terms and conditions and your continued use of the website acknowledge your agreement. The most current version of the ToU can be reviewed by clicking on the "sea.dragonnest.com" hypertext link located at the menu of our Web pages. If we change the ToU, we will communicate the changes to you before changes are made effective and we will update the Effective Date listed above. Your continued use of the Service after such notification of changes will constitute your acceptance of such changes.</span>
<strong>10. DISPUTE RESOLUTION</strong>
<span>10.1. Disputes.
<span>In an effort to accelerate resolution and reduce the cost of any dispute, controversy or claim related to, or arising out of, this agreement or any policy, document or agreement incorporated herein ( “Dispute”), you and Adventure Games agree to first attempt to negotiate any dispute, controversy, or claim, whether based on contract, tort, fraudulent misrepresentation, statute, regulation, constitution, common law, equity, or any other legal basis, that arises out of or relates to the Dispute (except as set forth in Section 10.4 below) informally for at least thirty (30) days before initiating any arbitration or court proceeding.
Negotiations will begin upon receipt of written notice by the party bringing the Dispute. Adventure Games will send its notice to your billing address and email you a copy to the email address you have provided to us.</span></span><span>10.2 Binding Arbitration.
<span>If a Dispute cannot be resolved through negotiations, then the Dispute must be submitted to binding arbitration (except for the circumstances described in Section 10 .4). Arbitration of a Dispute shall be a final and binding determination on you and Adventure Games. You should review this provision carefully. This arbitration provision limits your and Adventure Games’s ability to litigate claims in court and you and Adventure Games each agree to waive our respective rights to a jury trial.
The arbitration shall be commenced and conducted under the Streamlined Rules of the Judicial Arbitration and Mediation Service (the "JAMS") or, where appropriate, the JAMS International Rules, both of which are available at the JAMS website (www.jamsadr.com). This arbitration provision is made pursuant to a transaction involving interstate commerce, and the Federal Arbitration Act shall apply to the construction, interpretation, and enforceability of this agreement notwithstanding any other choice of law provision contained in this agreement. The arbitrator shall determine the scope and enforceability of this arbitration agreement, including whether a Dispute is subject to arbitration.
An arbitration is a proceeding before a neutral arbitrator, instead of before a judge or jury. Arbitration is less formal than a lawsuit in court, and provides more limited discovery. It follows different rules than court proceedings, and is subject to very limited review by courts. The arbitrator will issue a written decision and provide a statement of reasons if requested by either party. YOU ACKNOWLEDGE AND AGREE THAT YOU AND Adventure Games ARE GIVING UP THE RIGHT TO SUE IN COURT AND TO HAVE A TRIAL BEFORE A JUDGE OR JURY.</span></span><span>10.3 Restrictions.
<span>You and Adventure Games agree that any arbitration shall be limited to the Dispute between Adventure Games and you individually. SPECIFICALLY YOU ACKNOWLEDGE AND AGREE THAT:
• A CLAIM BY, OR ON BEHALF OF, OTHER PERSONS, WILL NOT BE CONSIDERED IN, JOINED WITH, OR CONSOLIDATED WITH, THE ARBITRATION PROCEEDINGS BETWEEN YOU AND Adventure Games;
• THERE IS NO RIGHT OR AUTHORITY FOR ANY DISPUTE TO BE ARBITRATED ON A CLASS-ACTION BASIS OR TO UTILIZE CLASS ACTION PROCEDURES; AND
• YOU WILL NOT HAVE THE RIGHT TO PARTICIPATE AS A CLASS REPRESENTATIVE, PRIVATE ATTORNEY GENERAL, OR AS A MEMBER OF ANY CLASS OF CLAIMANTS FOR ANY CLAIM SUBJECT TO ARBITRATION.
Any dispute regarding the prohibitions in the prior sections shall be resolved by the arbitrator in accordance with this agreement.</span></span><span>10.4. Exceptions to Negotiations and Arbitration.
<span>You and Adventure Games agree that the following Disputes are not subject to the above provisions concerning negotiations and binding arbitration:
• any Disputes seeking to enforce or protect, or concerning the validity of, any of your or Adventure Games’s intellectual property rights;
• any Dispute related to, or arising from, allegations of theft, piracy, invasion of privacy, or unauthorized use;
• any claim for injunctive relief;
• any claim within the jurisdictional limits of the small claims courts;
• any claim you are authorized to bring to the attention of any federal, state, or local government agencies that can, if the law allows, permit those authorities to seek relief from us on your behalf; and
• any claim you are authorized by applicable mandatory local law to bring to the attention of a court.</span></span><span>10.5. Location of Arbitration.
<span>If you are a resident of the Singapore, Philippines and Malaysia, any arbitration will take place at any reasonable location within Singapore for you. Any Dispute not subject to this Section shall be decided by a court of competent jurisdiction within South Korea, and you and Adventure Games agree to submit to the personal jurisdiction of that court.</span></span><span>10.6 Governing Law
<span>The ToU shall be governed by and construed in accordance with the law of Singapore, regardless of your place of residence, expressly excluding the UN Convention on Contracts for the International Sale of Goods.</span></span><span>10.7. Attorneys' Fees.
<span>If any legal action, including, without limitation, an action for arbitration or injunctive relief, is brought relating to this agreement or the breach hereof, the prevailing party in any final judgment or arbitration award, or the non-dismissing party in the event of a dismissal without prejudice, shall be entitled to the full amount of all reasonable expenses, including all court costs, arbitration fees and actual attorney fees paid or incurred in good faith.</span></span><span>10.8. Severability of Dispute Resolve.
<span>You and Adventure Games agree that if any portion of this Section 10 is found illegal or unenforceable, such portion shall be severed and the remainder of this Section 10 shall be given full force and effect. Any Dispute subject to any such portion of this Section 10 shall be decided by the arbitrator.</span></span>
<strong>11. GENERAL PROVISIONS</strong>
<span>11.1. Assignment.
<span>This agreement may not be assigned, in whole or part, whether voluntarily, by operation of law, or otherwise, by you without the prior written consent of Adventure Games. Adventure Games may assign, license, delegate or otherwise transfer its rights or obligations hereunder to any third party without restriction. Subject to the preceding sentences, the rights and liabilities of the parties hereto are binding on, and shall inure to the benefit of, the parties and their respective successors and permitted assigns. Any attempted assignment other than in accordance with this Section shall be null and void.</span></span><span>11.2. Waiver.
<span>The waiver by either party of a breach of or a default under any provision of this agreement, shall be in writing and shall not be construed as a waiver of any subsequent breach of or default under the same or any other provision of this agreement, nor shall any delay or omission on the part of either party to exercise or avail itself of any right or remedy that it has or may have hereunder operate as a waiver of any right or remedy.</span></span><span>11.3. Severability.
<span>If the application of any provision of this agreement to any particular facts or circumstances shall be held to be invalid or unenforceable by an arbitration panel or a court of competent jurisdiction, then (a) the validity and enforceability of such provision as applied to any other particular facts or circumstances and the validity of other provisions of this agreement shall not in any way be affected or impaired thereby, and (b) such provision shall be enforced to the maximum extent possible so as to effect the intent of the parties and reformed without further action by the parties to the extent necessary to make such provision valid and enforceable.</span></span><span>11.4. Export Controls.
<span>To the greatest extent permitted by applicable law, you shall abide by all applicable export laws and regulations in its use of the Service. The Service, or any part thereof, may not be downloaded or otherwise exported or re-exported to anyone in Singapore, Malaysia and Philippines. You represent and warrant that you are not located in, under the control of, or a national or resident of any such country or on any such list.</span></span><span>11.5. Captions and Section Headings.
<span>The captions and section and paragraph headings used in this agreement are inserted for convenience only and shall not affect the meaning or interpretation of this agreement.</span></span><span>11.6. Equitable Relief.
<span>You acknowledge and agree that due to the unique nature of this agreement, there can be no adequate remedy at law to compensate Adventure Games for your breach or threatened breach hereof; that any such breach or threatened breach will allow you or third parties to compete unfairly with Adventure Games resulting in irreparable harm to Adventure Games that would be difficult to measure; and, therefore, that upon any such breach or threat thereof, Adventure Games shall be entitled to seek injunctive and other appropriate equitable relief (without the necessity of proving actual damages, except where prohibited by applicable mandatory laws, or of posting a bond), in addition to whatever remedies it may have at law, hereunder, or otherwise.</span></span><span>11.7 No Waiver.
<span>Our failure to enforce any provision of this agreement or any applicable agreement shall in no way be construed to be a present or future waiver of such provision, nor in any way affect the right of any party to enforce each and every such provision thereafter. The express waiver by us of any provision, condition or requirement of this agreement or any applicable agreement shall not constitute a waiver of any future obligation to comply with such provision, condition or requirement.</span></span>
  © 2021 Adventure Games Games Inc. - All Rights Reserved


<strong>CODE OF CONDUCT</strong>

Effective Date : September 7th, 2021

When you become a part of the Adventure Games community, you are joining many other players worldwide. We understand that with a large player base, disputes and misunderstandings can arise from time to time. However, our in-game/online staff will do their best to resolve these as they happen.

There are a number of circumstances that can result in disciplinary action against your account, on both the forums and in-game. Appropriate action will be taken during any incidents of community disruption, violation of the EULA or ToU, or any other action that may be deemed inappropriate by the Adventure Games’s staff. All policies and agreements which govern your use of Adventure Games’s games and interactive services are available online here.

This Code of Conduct outlines the rules that you need to follow to help ensure that Adventure Games’s games, forums, and other interactive services are safe and fun for everyone.

<strong>A. Your Use of the Service Generally</strong>
<span>You will not use our games and interactive services for any unlawful purpose or in any manner not intended by Adventure Games.
We expect you to use our games and interactive services in a manner that is respectful of all other players.</span>
<strong>B.Technical Restrictions</strong>
<span>You will not use our games or interactive services to transmit any software or other materials that contain any viruses, worms, trojan horses, defects, date bombs, time bombs or other items of a destructive nature subject to Adventure Games’s regulations or policies.
You will not engage in spamming or flooding.
You will not remove, alter or conceal any copyright, trademark, patent or other proprietary rights notices contained in our games or interactive services.
You will not "frame" or "mirror" any part of our games, websites or interactive services without our prior written authorization.
You will not use any robot, spider, site search/retrieval application or other manual or automatic device or process to retrieve, index, "data mine" or in any way reproduce or circumvent the navigational structure or presentation of the games or interactive services, as well as any content contained therein.
You will not harvest or collect information about the games or interactive services, visitors to our websites, or users of our games or interactive services, without our prior express consent (which may be in the form of an API made available to you from time to time).
You will not download, copy, reproduce, republish, upload, post, transmit, modify, distribute or publicly display any of the content or information contained in our games or interactive services except as expressly authorized by the agreements between you and Adventure Games.
You will not host, provide matchmaking services for, or emulate or redirect the communications protocols used by us (or our designees) as part of the games or interactive services, including, without limitation, by protocol emulation, tunneling, reverse engineering, packet sniffing, re-routing, looping, modifying the game software or using a program to host a game.
You will not restrict or inhibit any other individual from using the services, including, without limitation, by means of "hacking" or defacing any portion of the services.
You will not institute an attack upon any server used in connection with our services or otherwise attempt to disrupt such servers.</span>
<strong>C. Cheating</strong>
<span>You will not exploit errors in design, features which are not documented and/or bugs to gain access that would otherwise not be available or to obtain any competitive advantage.
You will not modify the software made available to you, either as part of a game or an interactive service, to change the service. This includes, without limitation, creating cheats and/or hacks or using third-party software to access files we make available to you.
You will not reverse engineer, packet sniff, decompile or disassemble all or any portion of our games or interactive services.
You will not engage in using macros (e.g., "macroing"), auto-looting or robot play (i.e., "botting") or any other behavior that allows you (or any character you are controlling) to automatically function or effect any action in a game with or without your presence.
You will not use "packet sniffing," scripting and/or macroing software for any purpose whatsoever, or otherwise monitor the data streams generated by our games and interactive services.</span>
<strong>D. Improper Communications</strong>
<span>You will not give out personal information of other users (such as real name, physical address, IP address, email address, phone number, credit card number, etc.) in any way. This information could be used by others for illegal or harmful purposes. You are entirely responsible for the security of your account information and personally identifiable information.
You will not express or imply that any statements you make or actions you take are endorsed by Adventure Games.
You will not sell, advertise, or post information on hack, private servers (including sources thereto) or gold farming for games or interactive services, and you will not advertise, post information on or sell hacks for any other software or websites.
You will not use the games or interactive services to transmit any advertisements, solicitations, chain letters, pyramid schemes, investment opportunities or other unsolicited commercial communication.
Any non-game-related conversation that takes up a substantial amount of the forum, chat, or in-game chat space and prevents users from finding game-related information may be considered a violation of the Code of Conduct.</span>
<strong>E. Infringement of Intellectual Property or Other Proprietary Rights.</strong>
<span>Unauthorized use of another entity’s intellectual property is not allowed, including but not limited to: software, music, art, and other copyrighted, trademarked, or patented materials or trade secrets.
You will not use the games or interactive services to transmit any material, non-public information about companies without the authorization to do so.
You will not impersonate another person (including celebrities), indicate that you are a Adventure Games employee or a representative of Adventure Games, or attempt to mislead users by indicating that you represent Adventure Games or any Adventure Games partner or affiliate.</span>
<strong>F. Harassment</strong>
<span>You will not engage in rude, unlawful, harassing, vulgar, obscene, hateful, threatening, abusive or otherwise objectionable behavior, including, without limitation, intentionally looting, intentionally kill stealing, making sexual or other inappropriate comments.
You will not harass, abuse, bully, spam, scream at, threaten or stalk other users or encourage other players to do so.
You will not encourage harm or violence against people or animals, or promote self-harm in any manner.
You will not create or share any of the following through our games or interactive services: (i) Anything of a sexual or provocative nature; (ii) Content that a reasonable person would consider to be adult or borderline adult in nature; or (iii) Content that generally falls under the category of pornography
You will not attempt to obtain a password or other private account information from any other person or user of the Service.</span>
<strong>G. Prohibited Use of the Games and Interactive Services</strong>
<span>You will not exploit our games or interactive services for any commercial purpose, including selling of accounts, virtual currency or in-game items, the provision of "power leveling" services, etc.
Any content that facilitates or promotes illegal gambling, illegal content, pornography, piracy, illegal online pharmacies, illegal drugs, or criminal activities is prohibited.
Do not create or share any content that instructs users how to make bombs, weapons or drugs, or solicits involvement in behavior that is violent or illegal under applicable laws, rules and regulations.
Any content that facilitates or promotes underage drinking, consumption of illegal drugs, or socially irresponsible behavior due to alcohol or drug consumption (e.g., drinking and driving) is prohibited.
Do not create or share any content that facilitates, promotes, or contains terrorist threats or activities.
Do not create or share any content that facilitates, promotes, or contains references to viruses or malware.
Do not create or share any content that facilitates or promotes identity theft.</span>
<strong>H. Consequences of Violations</strong>
<span>If you violate the Code of Conduct, action(s) may be taken to address the violation, including but not limited to temporary suspensions, permanent character/game bans, or permanent IP blocks (prohibiting your access to any Adventure Games game or interactive service). Adventure Games will determine the appropriate course of action for violations of the Code of Conduct.
Adventure Games IS NOT OBLIGATED TO SEND YOU A WARNING BEFORE THESE ACTIONS OCCUR. If your account is suspended while you are participating in a tournament or competition, Adventure Games assumes no liability in the loss of any potential prizes or recognition related to the tournament or competition.
Adventure Games is not obligated to monitor every post or activity, but has the right to remove any post or take action against any user. Furthermore, Adventure Games reserves the right to remove at any time, without notice, any user-created content, account, or device from the games or interactive services for actions determined to be in violation of this Code of Conduct or Terms of Use.
UPON RECEIVING A PERMANENT BAN, ALL CONTENT LICENSES AND EYE CASH BALANCES ASSOCIATED WITH THE SUSPENDED ACCOUNT ARE FORFEITED.</span>

<strong>USER GENERATED CONTENT POLICY</strong>

Effective Date : September 7th, 2021

Certain features of our interactive services may allow you to create, upload and distribute user generated content (“UGC”). Adventure Games does not pre-screen UGC that may be posted or made available through the Service by players, and as such Adventure Games does not assume any responsibility or liability for content that is generated by users in connection with our games and interactive services.

You must have the legal right to create, upload and distribute UGC in connection with our games and interactive services. You may not upload or post any UGC that infringes the copyright, trademark or other intellectual property rights of Adventure Games or a third party. You may not upload UGC that violates the law, our EULA or Terms of Use and/or any third party's right of privacy or right of publicity.

Adventure Games does not assume any liability for any failure to remove, or any delay in removing UGC.  However, Adventure Games may, without prior notice to you and in its sole judgment, remove UGC that may infringe the intellectual property or other rights of Adventure Games or a third party. If you are a repeat infringer of Adventure Games's or a third party's intellectual property or other rights, Adventure Games may suspend or terminate your access to our games and interactive services without notice to you. YOU ACKNOWLEDGE AND AGREE THAT IF YOUR ACCESS TO OUR GAMES AND INTERACTIVE SERVICES ARE SUSPENDED OR TERMINATED, YOU ARE NOT ENTITLED TO A REFUND FOR ANY EYE CASH OR VIRTUAL ITEMS YOU HAVE OBTAINED. Our determinations regarding suspensions or terminations is made in our sole discretion and is final and binding on you.

You acknowledge and agree that you have no expectation of privacy concerning the transmission of gameplay or any User Generated Content, including without limitation chat text or voice communications. WE RESERVE THE RIGHT, AT ALL TIMES AND IN OUR SOLE DISCRETION, TO DISCLOSE ANY USER GENERATED CONTENT AND OTHER INFORMATION (INCLUDING WITHOUT LIMITATION CHAT TEXT, VOICE COMMUNICATIONS, AND GAMEPLAY FOOTAGE) FOR ANY REASON, including without limitation (a) to satisfy any applicable law, regulation, legal process or governmental request; (b) to enforce the terms of our Terms of Use or other applicable agreements and policies; (c) to protect our legal rights and remedies; (d) to protect the health or safety of anyone we believe may be threatened; or (e) to report a crime or other offensive behavior.

You agree that you will be personally responsible for your creation of UGC, and for all of your communications and activities done in connection with our games and interactive services, including any content you contribute.

You will indemnify and hold harmless Adventure Games, its parent, affiliates, and their respective employees, officers, and directors from any liability or damages arising from your conduct in the connection with our games and interactive services.

In exchange for use of our games and interactive services, and to the extent that your contributions through use of our games and interactive services give rise to any copyright interest, you hereby grant Adventure Games an exclusive, perpetual, irrevocable, fully transferable and sub-licensable worldwide right and license to use your contributions in any way and for any purpose in connection with the Software and related goods and services, including the rights to reproduce, copy, adapt, modify, perform, display, publish, broadcast, transmit, or otherwise communicate to the public by any means whether now known or unknown and distribute your contributions without any further notice or compensation to you of any kind for the whole duration of protection granted to intellectual property rights by applicable laws and international conventions. To the extent permitted by applicable law, you hereby waive any moral rights of paternity, publication, reputation, or attribution with respect to Adventure Games's and other players' use and enjoyment of such assets in connection with the Game and related goods and services under applicable law. The license grant to Adventure Games, and the above waiver of any applicable moral rights, survives any termination or revocation of any and all agreements between you and Adventure Games.


<strong>END USER LICENSE AGREEMENT</strong>

Effective Date : September 7th, 2021

THIS END USER LICENSE AGREEMENT (THIS “AGREEMENT”) IS ENTERED INTO BETWEEN Adventure Games GAMES, INC. (“Adventure Games”) AND YOU (“YOU” OR “YOUR”). IT IS IMPORTANT THAT YOU READ AND CAREFULLY UNDERSTAND THIS AGREEMENT. IF YOU DO NOT AGREE WITH ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT AND DO NOT WISH TO BE BOUND, DO NOT INSTALL THE GAME TO WHICH THIS AGREEMENT APPLIES OR OTHERWISE USE THE SOFTWARE TO WHICH THIS AGREEMENT APPLIES. IF YOU DO NOT ACCEPT THIS AGREEMENT, YOU WILL NOT BE ABLE TO ACCESS, DOWNLOAD OR USE THE SOFTWARE AND/OR THE SERVICE. Adventure Games RESERVES THE RIGHT IN ITS SOLE DISCRETION AT ANY TIME TO CHANGE ANY OF THE TERMS AND CONDITIONS CONTAINED IN THIS AGREEMENT. IF WE CHANGE THE TERMS OF THIS END USER LICENSE AGREEMENT, WE WILL COMMUNICATE THE CHANGES TO YOU PRIOR TO THE CHANGES BEING MADE EFFECTIVE.

¦  DEFINITIONS
For purposes of this Agreement, the following terms shall have the following meanings (terms capitalized but not defined in this Agreement shall have the meaning given to them in our Terms of Use):
<span>1. “Documentation” means the online, electronic or printed user guides and other documentation which Adventure Games makes generally available which describes the installation and use of the Software, regardless of how such documentation is accessed by you or delivered to you.
2. “Derivative Work” means a new or modified work that is based on or derived from a preexisting work, including, without limitation, a work that, in the absence of a license, would infringe the copyright in such preexisting work or that uses trade secrets or other proprietary information with respect to such preexisting work.
3. “Game” means the “Massively Multiplayer Online Role-Playing Game” or “Multiplayer Casual Online Game” or other game provided or serviced by Adventure Games, including the one to which this Agreement is appended.
4. “Intellectual Property Rights” means worldwide statutory and common law rights, existing now or in the future, associated with (a) issued patents, reissued or reexamined patents, revivals of patents, divisions, continuations and continuations-in-part of patents, all renewals and extensions thereof, utility models, and certificates of invention, regardless of country or formal name, published or unpublished nonprovisional and provisional patent applications, including the right to file other or further applications, reexamination proceedings, invention disclosures and records of invention; (b) works of authorship and visual artworks, including copyrights, moral rights, semiconductor topography and mask work rights, and all applications for registration, registrations, renewals and extensions of registrations thereof, together with all other interests accruing by reason of international copyright, semiconductor topography and mask work conventions; (c) proprietary information and materials, whether or not patentable or copyrightable, and whether or not reduced to practice, including without limitation all trade secrets, confidential information, business methods, ideas, research and development, inventions, designs, manufacturing and operating specifications and processes, know-how, formulae, customer and supplier lists, shop rights, designs, drawings, patterns, technical data, databases, data compilations and collections, computer programs, hardware, software and processes; (d) the trademarks, trade names, and service marks used by a party, whether registered or unregistered, together with the goodwill of the business associated therewith, and all applications for registration and registrations thereof, renewals thereof, the right to bring opposition and cancellation proceedings and any and all rights under the laws of trade dress, the respective stylistic marks and distinctive logotypes for such trademarks, trade names, and service marks and such other marks and logotypes as either party may designate from time to time in writing; and (e) all claims, causes of action and rights to sue for past, present and future infringement or use without consent of any of the foregoing rights.
5. “Service” shall mean the web sites provided by Adventure Games, its agents, designees, vendors or service providers and all related services and products, including, without limitation, Games hosted on servers controlled by Adventure Games, its agents, designees, vendors or service providers that are made available through the Internet for remote use by third parties.
6. “Software” means the Game software, in object code form only, and the media, Documentation and Updates for which you are granted a license pursuant to this Agreement.
7. “Term” shall have the meaning set forth in Section 9.
8. “Terms of Use” means Adventure Games's Terms of Use for the Service located at http://sea.dragonnest.com, as may be amended by Adventure Games from time to time.
9. “Updates” means the object code forms of any modifications, error corrections, bug fixes, new versions, or other updates of or to the Software that may be provided or otherwise made available hereunder by Adventure Games to you during the Term.</span>
<strong>1. PRECONDITIONS OF THE GRANT OF LICENSE</strong>
The grant of license as set forth in Section 4 below is specifically conditioned upon the following:
<span>1.1 You have accepted all of the terms in this Agreement and indicated your acceptance by selecting “YES,” “I AGREE,” or similar form of assent, as appropriate;
1.2 You will comply with all of the terms in this Agreement until such time as you have deleted all aspects of the Software from your machine;
1.3 You will use the Software only on an authorized device, running validly licensed copies of operating systems which the Game was designed to operate;
1.4 You will refrain from using any hacks, cracks, bots, or third party software which may modify, temporarily or permanently, the Software or the user experience of the Game, whether on your local machine or on servers which enable use of any features of the Game; and
1.5 You will comply with all requirements and obligations of the Terms of Use which is specifically incorporated into this Agreement and is made a part hereof.</span>
<strong>2. GAME ACCOUNTS</strong>
<span>2.1 Game Accounts. To play the Game(s), you may be required to create and maintain a Adventure Games ID, a Game-specific account, and, in some cases, a platform specific account (e.g., an account with Valve Corporation if the Game is distributed through Steam). To use or create a Adventure Games ID, you must register, or have previously established, an account on dragonnest.com. To use or create an account with a specific platform, you must register, or have previously established, an account with that platform.
2.2 Use of Adventure Games IDs. Creation and use of Adventure Games IDs, and subsequent use of are subject to the following terms and conditions:
2.2.1 When you create or update a Adventure Games ID, you must provide Adventure Games with accurate and up to date information that is personal to you, such as your name, address, phone number, and email address. Adventure Games’s retention of your personal information is subject to Adventure Games’s Privacy Policy, located at sea.dragonnest.com
2.2.2 Your use of the Games to interact with Adventure Games and other players is governed by Eydentity’s Terms of Use, which are available at sea.dragonnest.com. The Terms of Use are not meant to be exhaustive. The Terms of Use are incorporated into this Agreement by this reference, and are available for your review here.
2.2.3 You agree to pay all fees and applicable taxes incurred by you or anyone using your Eydentity ID. Adventure Games may revise the pricing for the goods and services offered in connection with the Games at any time.
2.3 Use of Platform-Specific Accounts. Use of a platform-specific account, which may be required to play a specific Game or utilize certain features, will be subject to the terms and conditions of that Platform.</span>
<strong>3. OWNERSHIP; GRANT OF LICENSE; RESTRICTIONS</strong>
<span>3.1 Ownership. As between Adventure Games and you, Adventure Games owns and shall retain all right, title and interest, including, without limitation, all Intellectual Property Rights, in and to the Software, and any portions thereof, including, without limitation, any copy or Derivative Work of the Software (or any portion thereof) and any Updates thereto. You agree to take any action reasonably requested by Adventure Games to evidence, maintain, enforce or defend the foregoing rights. You shall not take any action to jeopardize, encumber, limit or interfere in any manner with Adventure Games's ownership of and rights with respect to the Software, or any Derivative Work or Update thereof or thereto. You shall have only those rights in and to the Software and any Derivative Work or Update thereto as are expressly granted to you under this Agreement.
3.2 Limited Grant of License. Subject to the terms and conditions of this Agreement, Adventure Games hereby grants you a non-exclusive, nontransferable, non-sublicensable, limited right and license, during the Term, to:
3.2.1 Install a copy of the Software on one or more computers under your legitimate control;
3.2.2 Access and use the Software, solely in accordance with the Documentation and solely for your own personal, non-commercial, entertainment purposes.
3.2.3 Except as set forth in this Section, no other right or license of any kind is granted by Adventure Games to you hereunder with respect to the Software. Title to the Software is not transferred to you. You own the medium on which the Software is recorded, but we retain all right, title and interest in and to the Software, and all Intellectual Property Rights therein.
3.3 Restrictions. You hereby acknowledge and agree that you shall not use the Software for any purpose other than your personal, non-commercial entertainment purposes, and that you shall use the Software in accordance with all applicable laws, rules and regulations. Except as expressly provided herein, you shall not, and shall not permit any third party to:
3.3.1 Copy all or any portion of the Software, except as may be incidental to using the Software on your machine as permitted by this Agreement;
3.3.2 Exploit the Software, in its entirety or individual components, for any purpose not expressly authorized by Adventure Games Games, Inc., including, without limitation (i) gathering in-game currency, items, or resources for sale outside of Adventure Games’s authorized systems and channels; (ii) performing in-game services that disrupt the normal gameplay experience (e.g., power-leveling); or (iii) communicating or facilitating (by text, live audio communications, or otherwise) any commercial advertisement, solicitation or offer through or within the Software.
3.3.3 Create, utilize or transact in any in-game item created or copied by exploiting a design flaw, undocumented problem, or program bug in the Software
3.3.4 Decompile, disassemble or otherwise reverse engineer the Software, or any portion thereof, or determine or attempt to determine any source code, algorithms, methods or techniques used or embodied in the Software or any portion thereof;
3.3.5 Modify, translate, or create any Derivative Works based upon the Software except as may be provided by the Software itself or under other permission from Adventure Games;
3.3.6 Distribute, disclose, market, rent, lease, grant a security interest in, transfer, assign, sublicense, pledge or otherwise transfer the Software, in whole or in part, or any Cash Item (as defined in the Terms of Use) to any third party whatsoever;
3.3.7 Host, provide or develop matchmaking services for the Software;
3.3.8 Intercept, emulate or redirect the communication protocols used by Adventure Games, or its designees, in any way, including, without limitation, through protocol emulation, tunneling, packet sniffing, modifying or adding components to the Software, use of a “data mining” utility program to intercept, collect, read or “mine” information generated by the Software, or in any other way utilize a technique now known or hereafter developed that would allow for or otherwise make available unauthorized play of the Game or other use of the Software;
3.3.9 Create, use or maintain any unauthorized connections to the Software;
3.3.10 Remove or alter any copyright, trademark, or other Intellectual Property Right notices, legends, symbols, or labels appearing on or in the Software;
3.3.11 Disrupt or assist in the disruption of (i) any computer used to support the Software or a Game environment; or (ii) any other player’s Game experience. ANY ATTEMPT BY YOU TO DISRUPT THE SOFTWARE OR UNDERMINE THE LEGITIMATE OPERATION OF ANY GAME MAY BE A VIOLATION OF CRIMINAL AND CIVIL LAWS;
3.3.12 Violate Adventure Games’s Terms of Use (which are available at www.dragonnest.com); and
3.3.13 Use the Software for any purpose that (i) violates applicable law or regulation; or (ii) violates this Agreement.</span>
<strong>4. SERVICE</strong>
<span>4.1 Hosting of the Service. You acknowledge and agree that the Software is used to play the Game through the Service and that Adventure Games may, in its sole discretion, terminate or otherwise discontinue providing the Service at any time for any or no reason.
4.2 Updates. During the Term, Adventure Games may provide you with Updates as they are made generally available by Adventure Games. You acknowledge that, to the extent Adventure Games licenses some or all of the Software and/or other components of the Service from third party vendors (“Vendors”), such Vendors, and not Adventure Games, are responsible for creating Updates, if any, and making them available for installation or distribution. You acknowledge and agree that Adventure Games may, with your knowledge and prior consent, provide Updates to you remotely, including, without limitation, by accessing the computer in which you store the Software. Any Update provided or made available by Adventure Games hereunder shall be deemed part of the Software and shall be subject to the terms and conditions of this Agreement.
4.3 Game Policies. Your use of our Software and Service is conditioned on your acceptance of several different agreements. These agreements are:
4.3.1 This End User License Agreement;
4.3.2 The Privacy Policy;
4.3.3 The Terms of Use;
4.3.4 Additional terms that govern particular features or offers (for example, our Code of Conduct , our User Generated Content policy , etc.) (“Additional Terms”). A full list of Additional Terms can be found here ; and
4.3.5 Applicable third party terms that you may need to accept to utilize certain parts of the Service (e.g., payment processor terms; third party distribution platform terms, integration of social networking profiles, etc.).
The agreements are listed in terms of their priority and application to you. In the event of a conflict between provisions contained within any particular agreement, the agreement that is listed first shall control. For example, in the event of a conflict between these Terms of Use and the Privacy Policy, the Privacy Policy shall control. In the event of a conflict between the Additional Terms and this Agreement, this Agreement will control.
4.4 Your Further Obligations. You shall be solely responsible for any and all costs and fees in connection with accessing and using the Software and/or the Service, including, without limitation, Internet service provider fees, telecommunications fee and the costs of any and all equipment used by you in connection with the Software and/or the Service. You acknowledge that Adventure Games shall have no obligation to assist you in using or accessing the Software, except as expressly set forth in this Agreement. In addition, you agree to adhere at all times to the Terms of Use made available through the Service, as may be amended from time to time. Any changes to the Terms of Use will be communicated to you prior to the changes are made effective and your continued use of the Software, Game and/or Service after such notification of changes to the Terms of Use will constitute your acceptance of such changes.
4.5 Monitoring of the Service.
4.5.1 Adventure Games shall have the right to monitor and/or record your communications when you use the Software, and you acknowledge and agree that when you use the Software, that you have no expectation that your communications will be private. Adventure Games shall have the right to utilize recorded communications: (a) to satisfy any applicable law, regulation, legal process or governmental request; (b) to enforce the terms of this Agreement or any other Adventure Games policy; (c) to protect Adventure Games’s legal rights and remedies; (d) to protect the health or safety of anyone that Adventure Games believes may be threatened; or (e) to report a crime or other offensive behavior.
4.5.2 WHEN RUNNING, THE SOFTWWARE MAY MONITOR YOUR COMPUTER'S RANDOM ACCESS MEMORY (RAM) FOR UNAUTHORIZED THIRD PARTY PROGRAMS RUNNING CONCURRENTLY WITH THE GAME. AN "UNAUTHORIZED THIRD PARTY PROGRAM" AS USED HEREIN SHALL BE DEFINED AS ANY THIRD PARTY SOFTWARE PROHIBITED BY SECTION 3 ABOVE. IN THE EVENT THAT THE SOFTWARE DETECTS AN UNAUTHORIZED THIRD PARTY PROGRAM, (a) THE SOFTWARE MAY COMMUNICATE INFORMATION BACK TO Adventure Games, INCLUDING WITHOUT LIMITATION YOUR ACCOUNT NAME, DETAILS ABOUT THE UNAUTHORIZED THIRD PARTY PROGRAM DETECTED, AND THE TIME AND DATE; AND/OR (b) Adventure Games MAY EXERCISE ANY OR ALL OF ITS RIGHTS UNDER THIS AGREEMENT, WITH OR WITHOUT PRIOR NOTICE TO THE USER. Additionally, certain Games may include a tool that will allow your computer system to forward information to Adventure Games in the event that the Game crashes, including system and driver data, and consent to Adventure Games being able to receive this data.</span>
<strong>5. CONFIDENTIAL INFORMATION</strong>
<span>5.1 Confidential Information. You acknowledge that, in the course of using the Software and exercising your rights under this Agreement, you may obtain confidential information relating to the Software, the Service or Adventure Games and its Vendors or other parties (“Confidential Information”). Such Confidential Information shall, as between you and Adventure Games, belong solely to Adventure Games and shall include, without limitation, the Software (including any and all Derivative Works and Updates), the existence of and terms of this Agreement, trade secrets, know-how, inventions (whether or not patentable), techniques, processes, programs, ideas, algorithms, formulas, schematics, testing procedures, software design and architecture, computer code, internal documentation, design and functional specifications, product requirements, problem reports, performance information, documents, and other technical, business, product, marketing, third party customers, and financial information, plans and data.
5.2 Use and Disclosure Restrictions. You hereby acknowledge and agree that the Confidential Information constitutes and contains valuable proprietary information and trade secrets of Adventure Games, and embodies substantial creative efforts and confidential information, ideas, and expressions. Accordingly, you agree: (a) to protect the Confidential Information from unauthorized dissemination and use; (b) to use the Confidential Information only for the performance of your obligations and in connection with the exercise of your rights hereunder; (c) not to disclose or otherwise provide to any third party, without the prior written consent of Adventure Games, any Confidential Information or any part or parts thereof; (d) to undertake whatever action is necessary to prevent or remedy (or authorize Adventure Games to do so in your name) any breach of your confidentiality obligations set forth herein; (e) not to remove or destroy any proprietary or confidential legends or markings placed upon or contained within the Software, or on any other Confidential Information provided to you by Adventure Games; and (f) not to develop any other materials, products, or services containing any of the concepts or ideas contained in the Software or Service or any other Confidential Information.
5.3 Exclusions. The foregoing restrictions pertaining to the Confidential Information shall not apply with respect to any Confidential Information that: (a) was or becomes publicly known through no fault of you; (b) was known by you before receipt from Adventure Games, as evidenced by your contemporaneous written records, (c) becomes known to you without confidential or proprietary restriction from a source other than Adventure Games that does not owe a duty of confidentiality to Adventure Games with respect to such Confidential Information; or (d) is independently developed by you without use of the Confidential Information. In addition, you may use or disclose Confidential Information to the extent (i) expressly approved by an authorized representative of Adventure Games in writing, and (ii) you are legally compelled to disclose such Confidential Information; provided, however, prior to any such compelled disclosure you shall cooperate fully with Adventure Games in protecting against any such disclosure and/or obtaining a protective order narrowing the scope of such disclosure and/or use of the Confidential Information.</span>
<strong>6. NO WARRANTY/LIMITATION OF LIABILITY</strong>
<span>6.1 Disclaimer of Warranties. THE SOFTWARE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, Adventure Games AND ITS PARENTS, SUBSIDIARIES, AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, PARTNERS, SPONSORS AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, ACCURACY, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE. Adventure Games AND ITS AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS, PARTNERS AND AGENTS DO NOT WARRANT THAT YOUR USE OF THE SOFTWARE WILL BE UNINTERRUPTED, ERROR-FREE OR SECURE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SOFTWARE, AND/OR THE SERVER(S), SYSTEM(S) AND NETWORK(S) ON WHICH THE SOFTWARE IS HOSTED AND/OR OPERATES, ARE OR WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. YOU ACKNOWLEDGE THAT YOU ARE RESPONSIBLE FOR OBTAINING AND MAINTAINING ALL TELEPHONE, COMPUTER HARDWARE AND OTHER EQUIPMENT NEEDED TO ACCESS AND USE THE SOFTWARE AND ALL CHARGES RELATED THERETO. YOU ASSUME ALL RESPONSIBILITY AND RISK FOR YOUR USE OF THE SOFTWARE AND YOUR RELIANCE THEREON. NO OPINION, ADVICE OR STATEMENT OF Adventure Games OR ITS AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS, PARTNERS, AGENTS OR THIRD PARTY USERS, WHETHER MADE IN OR ON THE SOFTWARE OR OTHERWISE, SHALL CREATE ANY WARRANTY. YOUR USE OF THE SOFTWARE IS ENTIRELY AT YOUR OWN RISK.
6.2 Limitation of Liability.
6.2.1 Adventure Games AND ITS LICENSORS MAKE NO PROMISE OR WARRANTY THAT THE GAME OR SOFTWARE WILL WORK PROPERLY. YOU ACKNOWLEDGE AND AGREE THAT Adventure Games IS NOT RESPONSIBLE OR LIABLE FOR (1) ANY VIRUSES OR SOFTWARE DISABLING FEATURES THAT AFFECT YOUR ACCESS TO OR USE OF THE SOFTWARE, (2) ANY INCOMPATIBILITY BETWEEN THE SOFTWARE, AND OTHER SERVICES, SOFTWARE AND HARDWARE, OR (3) ANY DELAYS OR FAILURES YOU MAY EXPERIENCE IN INITIATING, CONDUCTING OR COMPLETING ANY TRANSMISSIONS OR TRANSACTIONS IN CONNECTION WITH THE SOFTWARE IN AN ACCURATE OR TIMELY MANNER.
6.2.2 Adventure Games does not ensure continuous, error free, secure or virus-free operation of any online, multi-player or downloadable portions of the Software or continued operation or availability of any given server.
6.2.3 Adventure Games is not liable for any delay or failure to perform resulting from any causes beyond our reasonable control. Further, Adventure Games cannot and does not promise or ensure that you will be able to access the online, multi-player or downloadable portions of the Software whenever you want, and there may be extended periods of time when you cannot access such portions of the Software.
6.2.4 NEITHER Adventure Games NOR ANY OF ITS PARENTS, SUBSIDIARIES, AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS OR PARTNERS, NOR Adventure Games'S OR OTHER ENTITIES' DIRECTORS, OFFICERS, EMPLOYEES, CONSULTANTS, AGENTS, ATTORNEYS OR OTHER REPRESENTATIVES, ARE RESPONSIBLE OR LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES OF ANY KIND (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS, LOSS OF DATA OR LOST PROFITS), UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY ARISING OUT OF OR RELATING IN ANY WAY TO THE SOFTWARE, EVEN IF Adventure Games (OR SUCH OTHER ENTITIES OR PERSONS) HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. YOUR SOLE AND EXCLUSIVE REMEDY FOR DISSATISFACTION WITH THE SOFTWARE, OR ANY PART THEREOF, IS TO STOP USING THE SOFTWARE. THE MAXIMUM AGGREGATE LIABILITY OF Adventure Games FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, SHALL BE TWENTY U.S. DOLLARS.
6.3 Other. Without limiting the foregoing, Adventure Games shall have no obligations, responsibilities and/or liabilities if any nonconformance or failure of, or error in, the Software is caused by: (a) use of any attachment, feature, hardware, software or device in connection with the Software not supplied by Adventure Games; (b) transportation, neglect or misuse of the Software or any use of the Software that is not in accordance with this Agreement and/or the Documentation; (c) alteration, modification, or enhancement of the Software other than by Adventure Games; or (d) failure to provide a suitable installation or use environment for all or any part of the Software. This clause shall be valid and enforceable to the fullest extent permitted by law.</span>
<strong>7. INDEMNIFICATION</strong>
<span>As a condition of your access to and use of the Software, you hereby agree to indemnify, defend, and hold Adventure Games, our parents, subsidiaries, affiliates, independent contractors, licensors, suppliers, advertisers, partners, sublicensees and sponsors, and our and their directors, officers, employees, consultants, agents, attorneys and other representatives, harmless from and against, any and all claims, damages, losses, liabilities, costs (including reasonable attorneys' fees) and other expenses that arise directly or indirectly out of or from: (a) your use, operation or combination of the Software with non-Adventure Games software, data, equipment or documentation if liability would have been avoided but for such use, operation, or combination; (b) your use of other than the then-current, unaltered version of the Software; (c) your activities after Adventure Games has notified you that Adventure Games believes such activities may result in infringement or otherwise violate the rights of Adventure Games or any third party; (d) any modifications to the Software made by you; (e) your breach or alleged breach of this Agreement; and (f) your violation of any applicable law or the rights of any other person.</span>
<strong>8. CHANGES</strong>
<span>8.1 Alterations to the Agreement. Adventure Games may create updated versions of this Agreement (each a “New Agreement”) as the Software, the Games, and the law evolve. This Agreement will terminate immediately upon the introduction of a New Agreement. New Agreements will not be applied retroactively. You will be given an opportunity to review the New Agreement before choosing to accept or reject its terms. If you accept the New Agreement, and if your Software-related account remains in good standing, you will be able to continue using the Software subject to the terms of the New Agreement. If you decline to accept the New Agreement, or if you cannot comply with the terms of the New Agreement, you will no longer be permitted to use the Software.
8.2 Changes to the Software.  Adventure Games may change, modify, suspend, or discontinue any aspect of the Game(s) or Software at any time, including removing items, or revising the effectiveness of items in an effort to balance a Game. Adventure Games may also impose limits on certain features or restrict your access to parts or all of the Software without notice or liability.</span>
<strong>9. TERM AND TERMINATION</strong>
<span>9.1 Term. This Agreement shall commence on the date you indicate your acceptance of this EULA and shall continue until termination in accordance with this Section.
9.2 Termination. This Agreement shall remain effective until terminated in accordance with its terms. You are entitled to terminate this agreement at any time by uninstalling all aspects of the Software to which you have access and by submitting to Adventure Games a request to permanently delete all account information linked to you. Adventure Games may terminate this Agreement in the event that you fail to comply with the terms and conditions contained herein or the terms and conditions contained in the Terms of Use. Without limiting the foregoing, Adventure Games reserves the right to immediately terminate this Agreement, and/or your use of the Software or any portion thereof, at any time and for any reason, with or without cause.
9.3 Effect of Termination. Upon the expiration or termination of this Agreement, all rights and licenses granted to you hereunder shall immediately terminate. Upon termination or expiration of this Agreement, you shall, at your sole expense, return to Adventure Games (or destroy, at Adventure Games's sole election) all Software and Confidential Information (and all copies and extracts thereof) then in your possession or under your control. Termination of this Agreement shall not act as a waiver of any breach of this Agreement and shall not act as a release of your liability for breach of your obligations under this Agreement. Adventure Games shall not be liable to you for damages of any kind solely as a result of terminating this Agreement in accordance with its terms. Adventure Games's termination of this Agreement shall be without prejudice to any other right or remedy that it may have at law or in equity, and shall not relieve you of breaches occurring prior to the effective date of such termination. The provisions of Sections 1, 2, 4, 6, 7, 8 and 11 shall survive the expiration or any termination of this Agreement.</span>
<strong>10. DISPUTE RESOLUTION</strong>
<span>10.1 Disputes. In an effort to accelerate resolution and reduce the cost of any dispute, controversy or claim related to, or arising out of, this Agreement or any policy, document or agreement incorporated herein (“Dispute”), you and Adventure Games agree to first attempt to negotiate any dispute, controversy, or claim, whether based on contract, tort, fraudulent misrepresentation, statute, regulation, constitution, common law, equity, or any other legal basis, that arises out of or relates to the Dispute (except as set forth in Section 10.4 below) informally for at least thirty (30) days before initiating any arbitration or court proceeding.
Negotiations will begin upon receipt of written notice by the party bringing the Dispute. Adventure Games will send its notice to your billing address and email you a copy to the email address you have provided to us.
10.2 Binding Arbitration.
10.2.1 If a Dispute cannot be resolved through negotiations, then the Dispute must be submitted to binding arbitration (except for the circumstances described in Section 10.4). Arbitration of a Dispute shall be a final and binding determination on you and Adventure Games. You should review this provision carefully. This arbitration provision limits your and Adventure Games’s ability to litigate claims in court and you and Adventure Games each agree to waive our respective rights to a jury trial.
10.2.2 The arbitration shall be commenced and conducted under the Streamlined Rules of the Judicial Arbitration and Mediation Service (the "JAMS") or, where appropriate, the JAMS International Rules, both of which are available at the JAMS website (www.jamsadr.com). This arbitration provision is made pursuant to a transaction involving interstate commerce, and the Federal Arbitration Act (the “FAA”) shall apply to the construction, interpretation, and enforceability of this Agreement notwithstanding any other choice of law provision contained in this Agreement. The arbitrator shall determine the scope and enforceability of this arbitration agreement, including whether a Dispute is subject to arbitration.
10.2.3 An arbitration is a proceeding before a neutral arbitrator, instead of before a judge or jury. Arbitration is less formal than a lawsuit in court, and provides more limited discovery. It follows different rules than court proceedings, and is subject to very limited review by courts. The arbitrator will issue a written decision and provide a statement of reasons if requested by either party. YOU UNDERSTAND AND AGREE THAT YOU AND Adventure Games ARE GIVING UP THE RIGHT TO SUE IN COURT AND TO HAVE A TRIAL BEFORE A JUDGE OR JURY.
10.3 Restrictions. You and Adventure Games agree that any arbitration shall be limited to the Dispute between Adventure Games and you individually. YOU ACKNOWLEDGE AND AGREE THAT:
10.3.1 A CLAIM BY, OR ON BEHALF OF, OTHER PERSONS, WILL NOT BE CONSIDERED IN, JOINED WITH, OR CONSOLIDATED WITH, THE ARBITRATION PROCEEDINGS BETWEEN YOU AND Adventure Games;
10.3.2 THERE IS NO RIGHT OR AUTHORITY FOR ANY DISPUTE TO BE ARBITRATED ON A CLASS-ACTION BASIS OR TO UTILIZE CLASS ACTION PROCEDURES; AND
10.3.3 YOU WILL NOT HAVE THE RIGHT TO PARTICIPATE AS A CLASS REPRESENTATIVE, PRIVATE ATTORNEY GENERAL, OR AS A MEMBER OF ANY CLASS OF CLAIMANTS FOR ANY CLAIM SUBJECT TO ARBITRATION.
10.3.4 Any dispute regarding the prohibitions in the prior sections shall be resolved by the arbitrator in accordance with this Agreement.
10.4 Exceptions to Negotiations and Arbitration. You and Adventure Games agree that the following Disputes are not subject to the above provisions concerning negotiations and binding arbitration: 10.4.1 any Disputes in countries that prohibit by law submission of Disputes to binding arbitration;
10.4.2 any Disputes seeking to enforce or protect, or concerning the validity of, any of your or Adventure Games’s intellectual property rights;
10.4.3 any Dispute related to, or arising from, allegations of theft, piracy, invasion of privacy, or unauthorized use;
10.4.4 any claim for injunctive relief;
10.4.5 any claim within the jurisdictional limits of the small claims courts; and
10.4.6 any claim you are authorized to bring to the attention of any federal, state, or local government agencies that can, if the law allows, permit those authorities to seek relief from us on your behalf.
10.5 Location of Arbitration. If you are a resident of the United States, any arbitration will take place at any reasonable location within the United States convenient for you. For permanent residents of the EU, any arbitration shall be initiated in the Grand Duchy of Luxembourg. For all other users, any arbitration shall be initiated in the County of Santa Clara, State of California, United States of America. Any Dispute not subject to this Section shall be decided by a court of competent jurisdiction within the County of Santa Clara, State of California, United States of America, and you and Adventure Games agree to submit to the personal jurisdiction of that court.
10.6 Governing Law. You agree that this Agreement shall be deemed to have been made and executed in the State of California, U.S.A., and any Dispute arising hereunder shall be resolved in accordance with the law of California. You agree that any claim asserted in any legal proceeding by you against Adventure Games shall be commenced and maintained exclusively in any state or federal court located in Santa Clara County, California, having subject matter jurisdiction with respect to the dispute between the parties and you hereby consent to the exclusive jurisdiction of such courts. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded, regardless of your place of residence
10.7 Attorneys' Fees. If any legal action, including, without limitation, an action for arbitration or injunctive relief, is brought relating to this Agreement or the breach hereof, the prevailing party in any final judgment or arbitration award, or the non-dismissing party in the event of a dismissal without prejudice, shall be entitled to the full amount of all reasonable expenses, including all court costs, arbitration fees and actual attorney fees paid or incurred in good faith.
10.8 Severability of Dispute Resolve. You and Adventure Games agree that if any portion of this Section 10 is found illegal or unenforceable, such portion shall be severed and the remainder of this Section 10 shall be given full force and effect. Any Dispute subject to any such portion of this Section 10 shall be decided by the arbitrator.</span>
<strong>11. GENERAL PROVISIONS</strong>
<span>11.1 Assignment. This Agreement may not be assigned, in whole or part, whether voluntarily, by operation of law, or otherwise, by you without the prior written consent of Adventure Games. Adventure Games may assign, license, delegate or otherwise transfer its rights or obligations hereunder to any third party without restriction. Subject to the preceding sentences, the rights and liabilities of the parties hereto are binding on, and shall inure to the benefit of, the parties and their respective successors and permitted assigns. Any attempted assignment other than in accordance with this Section shall be null and void.
11.2 Waiver. The waiver by either party of a breach of or a default under any provision of this Agreement, shall be in writing and shall not be construed as a waiver of any subsequent breach of or default under the same or any other provision of this Agreement, nor shall any delay or omission on the part of either party to exercise or avail itself of any right or remedy that it has or may have hereunder operate as a waiver of any right or remedy.
11.3 Severability. If the application of any provision of this Agreement to any particular facts or circumstances shall be held to be invalid or unenforceable by an arbitration panel or a court of competent jurisdiction, then (a) the validity and enforceability of such provision as applied to any other particular facts or circumstances and the validity of other provisions of this Agreement shall not in any way be affected or impaired thereby, and (b) such provision shall be enforced to the maximum extent possible so as to effect the intent of the parties and reformed without further action by the parties to the extent necessary to make such provision valid and enforceable.
11.4 Relationship of the Parties. Nothing contained in this Agreement shall be deemed or construed as creating a joint venture, partnership, agency, employment or fiduciary relationship between the parties. Neither party, nor either party's agents, have any authority of any kind to bind the other party in any respect whatsoever, and the relationship of the parties is, and at all times shall continue to be, that of independent contractors.
11.5 Force Majeure. Neither party shall be responsible or have any liability for any delay or failure to perform to the extent due to unforeseen circumstances or causes beyond its reasonable control, including, without limitation, acts of God, earthquake, fire, flood, embargoes, labor disputes and strikes, riots, war, acts of a public enemy, error in the coding of electronic files, Internet or other network “brownouts” or failures, power failures, novelty of product manufacture or other unanticipated product development problems, and acts of civil and military authorities.
11.6 Government Rights. If you are, or are entering into this Agreement on behalf of, any agency or instrumentality of Korean Government, the Software is “commercial computer software” and “commercial computer software documentation,” and pursuant to FAR 12.212 or DFARS 227.7202, and their successors, as applicable, use, reproduction and disclosure of the Software is governed by the terms of this Agreement.
11.7 Export Controls. You shall abide by all applicable export laws and regulations in its use of the Software. The Software, or any part thereof, may not be downloaded or otherwise exported or re-exported anyone in Singapore, Malaysia and Philippines. You represent and warrant that you are not located in, under the control of, or a national or resident of any such country or on any such list.
11.8 Captions and Section Headings. The captions and Section and paragraph headings used in this Agreement are inserted for convenience only and shall not affect the meaning or interpretation of this Agreement.
11.9 Equitable Relief. You acknowledge and agree that due to the unique nature of this Agreement, there can be no adequate remedy at law to compensate Adventure Games for your breach or threatened breach hereof; that any such breach or threatened breach will allow you or third parties to compete unfairly with Adventure Games resulting in irreparable harm to Adventure Games that would be difficult to measure; and, therefore, that upon any such breach or threat thereof, Adventure Games shall be entitled to injunctive and other appropriate equitable relief (without the necessity of proving actual damages or of posting a bond), in addition to whatever remedies it may have at law, hereunder, or otherwise.
11.10 Entire Agreement; Amendment. This Agreement (together with the Terms of Use) constitute the entire agreement between the parties concerning the subject matter hereof, and supersedes (a) all prior or contemporaneous representations, discussions, proposals, negotiations, conditions, agreements, and communications, whether oral or written, between the parties relating to the subject matter of this Agreement; and (b) all past courses of dealing and industry custom.</span>
© 2021 Adventure Games LLC Inc. - All Rights Reserved
	</div>
  </div>

</div>
<div class="container">
        <form action="register.php" method="post">
		<br>
			<p class="title">REGISTRATION</p>
			<br>
               <label for="Email" class="EmailN">EMAIL</label>
				<div id="emailid">
            		<input class="email" type="email" id="Email" name="mail" required>
					</div>
					
            	<label for="Username" class="UserN">USERNAME</label>
				<div id="userid">
            		<input class="user" type="text" id="Username" name="username" pattern="[A-Za-z0-9\-_\.]{6,12}" required>
					</div>
					
            		 <label for="Password" class="PassN">PASSWORD</label>
					 <div id="passid">
                    <input class="pass" id="Password" type="password" name="password" pattern="#[='\"]|true|false+#i.{4,20}$" required>
					</div>
					
					<br>
					
					<center>
					<input type="checkbox" name="terms" class="form-checkbox h-5 w-5 text-red-600" required><span class="ml-2 text-gray-700 jspan">I agree to the<a id="myBtn" class="ml-2 text-red-700">Condition and Terms of Agreement.</a></span>
					</center>
					
					<br>
					<br>
					
					<div id="input-button">
			<input id="submitter" type="submit" class="focus:outline-none text-red-600 text-sm py-2.5 px-5 rounded-md border border-red-600" value="Sign-up">
		  </div>
		</form>
	</div>
	<footer class="foot">
		<p class="foot-paragraph">©2021 Adventure Games LLC Inc.</p>
		<div class="svg">
	<a href="#" class="discord"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M20.222 0c1.406 0 2.54 1.137 2.607 2.475V24l-2.677-2.273l-1.47-1.338l-1.604-1.398l.67 2.205H3.71c-1.402 0-2.54-1.065-2.54-2.476V2.48C1.17 1.142 2.31.003 3.715.003h16.5L20.222 0zm-6.118 5.683h-.03l-.202.2c2.073.6 3.076 1.537 3.076 1.537c-1.336-.668-2.54-1.002-3.744-1.137c-.87-.135-1.74-.064-2.475 0h-.2c-.47 0-1.47.2-2.81.735c-.467.203-.735.336-.735.336s1.002-1.002 3.21-1.537l-.135-.135s-1.672-.064-3.477 1.27c0 0-1.805 3.144-1.805 7.02c0 0 1 1.74 3.743 1.806c0 0 .4-.533.805-1.002c-1.54-.468-2.14-1.404-2.14-1.404s.134.066.335.2h.06c.03 0 .044.015.06.03v.006c.016.016.03.03.06.03c.33.136.66.27.93.4a8.18 8.18 0 0 0 1.8.536c.93.135 1.996.2 3.21 0c.6-.135 1.2-.267 1.8-.535c.39-.2.87-.4 1.397-.737c0 0-.6.936-2.205 1.404c.33.466.795 1 .795 1c2.744-.06 3.81-1.8 3.87-1.726c0-3.87-1.815-7.02-1.815-7.02c-1.635-1.214-3.165-1.26-3.435-1.26l.056-.02zm.168 4.413c.703 0 1.27.6 1.27 1.335c0 .74-.57 1.34-1.27 1.34c-.7 0-1.27-.6-1.27-1.334c.002-.74.573-1.338 1.27-1.338zm-4.543 0c.7 0 1.266.6 1.266 1.335c0 .74-.57 1.34-1.27 1.34c-.7 0-1.27-.6-1.27-1.334c0-.74.57-1.338 1.27-1.338z" fill="#626262"/></svg></a>
	<a href="#" class="facebook"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><g fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M0 12.067C0 18.033 4.333 22.994 10 24v-8.667H7V12h3V9.333c0-3 1.933-4.666 4.667-4.666c.866 0 1.8.133 2.666.266V8H15.8c-1.467 0-1.8.733-1.8 1.667V12h3.2l-.533 3.333H14V24c5.667-1.006 10-5.966 10-11.933C24 5.43 18.6 0 12 0S0 5.43 0 12.067z" fill="#626262"/></g></svg></a>
	</div>
	</footer>
	<script>
var modal = document.getElementById("myModal");

var btn = document.getElementById("myBtn");

var span = document.getElementsByClassName("close")[0];

btn.onclick = function() {
  modal.style.display = "block";
}
span.onclick = function() {
  modal.style.display = "none";
}
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
	</script>
</body>
</html>